class RemoteType:
    AIR_CONDITIONER = "Air Conditioner"
    TV = "TV"
    LIGHT = "Light"
    IPTV_STREAMER = "IPTV/Streamer"
    SET_TOP_BOX = "Set Top Box"
    DVD = "DVD"
    FAN = "Fan"
    PROJECTOR = "Projector"
    CAMERA = "Camera"
    AIR_PURIFIER = "Air Purifier"
    SPEAKER = "Speaker"
    WATER_HEATER = "Water Heater"
    VACUUM_CLEANER = "Vacuum Cleaner"
    OTHERS = "Others"


class DeviceType:
    HUB = "Hub"
    HUB_PLUS = "Hub Plus"
    HUB_MINI = "Hub Mini"
    BOT = "Bot"
    CURTAIN = "Curtain"
    PLUG = "Plug"
    PLUG_MINI_US = "Plug Mini (US)"
    PLUG_MINI_JP = "Plug Mini (JP)"
    METER = "Meter"
    METER_PLUS = "MeterPlus"
    MOTION_SENSOR = "Motion Sensor"
    CONTACT_SENSOR = "Contact Sensor"
    COLOR_BULB = "Color Bulb"
    HUMIDIFIER = "Humidifier"
    SMART_FAN = "Smart Fan"
    STRIP_LIGHT = "Strip Light"
    CEILING_LIGHT = "Ceiling Light"
    CEILING_LIGHT_PRO = "Ceiling Light Pro"
    INDOOR_CAM = "Indoor Cam"
    PAN_TILT_CAM = "Pan/Tilt Cam"
    REMOTE = "Remote"
    LOCK = "Smart Lock"
    KEYPAD = "Keypad"
    KEYPAD_TOUCH = "Keypad Touch"
    ROBOT_VACUUM_CLEANER_S1_PLUS = "Robot Vacuum Cleaner S1"
    ROBOT_VACUUM_CLEANER_S1 = "Robot Vacuum Cleaner S1 Plus"
